admin_server:
  enabled: true
  listen: 0.0.0.0:8889 [::]:8889
cameras:
  gopro-hero-9:
    gopro_day_settings: # you can can the profile IDs by sending sending a curl to http://10.5.5.9/gopro/camera/presets/get
      profile_id: 65536 # Specific profile for GoPro Hero 11 Single photo mode
      settings:
        '125': 3
    gopro_night_settings:
      profile_id: 65539 #Specific to Gopro Hero 11. Night mode locks the ISO at 100
    gopro_ip: 10.5.5.9 # Default for GoPro over Wifi (when the GoPro is an access point)
    lat: 37
    lon: -122
    postprocessing:
    - area: 139,892,5568,3254
      type: crop
    - background_color: "(100, 100, 100)"
      color: white
      enabled: true
      position: top_right
      size: 36
      type: timestamp
    - type: sun_path
      enabled: true
      overlay_width: 1000  # Width of the overlay in pixels
      position: "top_center" # e.g., top_left, bottom_right, etc.
      padding: 5 # Optional padding from the edge
      # Bar thickness options still work
      major_bar_width: 4
      minor_bar_width: 2
      overlay_bar_width: 4
      overlay_rect_width: 15
      overlay_border_width: 3
      overlay_border_color: "white"
      major_bar_color: "grey"
      minor_bar_color: "#333333" # Can be hex code
      overlay_bar_color: "rgba(255, 0, 0, 0.5)" # Can be RGBA for transparency
      overlay_rect_height_ratio: 1.0
      background_color: "rgba(255, 255, 255, 0.3)"
      sun_arc_color: "rgba(255, 165, 0, 0.65)"
    - angle: 180
      type: rotate
    - width: 3840
      type: resize
    - enabled: true
      type: gather_metrics
    sky_area: 0,0,1.0,0.6
    ssim_area: 0,0,1.0,0.6
    ssim_setpoint: 0.87
    sunrise_sunset: #Slows down the timelapse around the sunrise sunset based on your GPC location
      enabled: true
global:
  log_dir: /srv/fenetre/logs #Not really used anymore
  timezone: America/Los_Angeles
  ui:
    fullscreen_camera: gopro-hero-11
    landing_page: fullscreen
  work_dir: /srv/fenetre/data
  storage_management:
    check_interval_s: 60
    dry_run: false
    enabled: true
    work_dir_max_size_GB: 100
http_server:
  enabled: true
timelapse:
  ffmpeg_2pass: true
  ffmpeg_options: -c:v libvpx-vp9 -b:v 5M -deadline best -speed 0
  file_extension: webm
  framerate: 60
  frequent_timelapse:
    ffmpeg_2pass: false
    # Raspberry pi 4 HW accel will be used if on Pi and ffmpeg_options isn't selected
    # Intel NUC hardware acceleration
    ffmpeg_options: -extbrc 1 -look_ahead 1 -look_ahead_depth 60 -g 120 -bf 3 -preset
      veryslow -c:v hevc_qsv -b:v 4M -maxrate 5M -bufsize 8M -profile:v main -movflags
      +faststart
    file_extension: mp4
    framerate: 30
    interval_s: 1200
