services:
  fenetre:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fenetre_app
    restart: unless-stopped
    user: "1000:1000"
    shm_size: '256m'
    ports:
      - "8888:8888"  # For python unsecure public web interface
      - "8889:8889"  # For admin interface
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    group_add:
      - video # For Intel OpenCL
      - render
    volumes:
      # Mount the local config.yaml to the container's /app/config.yaml
      - ./config.yaml:/srv/fenetre/config.yaml
      # Mount the local directory /srv/fenetre/data to /app/data in the container
      - /srv/fenetre/data:/srv/fenetre/data
      # Optional log to directory instead of stdout
      - /srv/fenetre/logs:/srv/fenetre/logs
      # OpenCL
      - /etc/OpenCL/vendors:/etc/OpenCL/vendors

  nginx:
    image: nginx:alpine
    container_name: fenetre_webserver
    restart: unless-stopped
    ports:
      - "8887:80"  # Robust static nginx public web server
        #      - "5803:443" # Expose port 5803 on the host to port 443 for HTTPS in the container
    volumes:
      # Mount the same data directory to the Nginx container to serve it
      - /srv/fenetre/data:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount SSL certificates into the Nginx container
      #      - ./ssl/cert.pem:/etc/nginx/ssl/cert.pem:ro
      #      - ./ssl/key.pem:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - fenetre
