class GoProEnums:
    STATUS_NAMES = {
        1: "Battery Present",
        2: "Internal Battery Bars",
        6: "Overheating",
        8: "Busy",
        9: "Quick Capture",
        10: "Encoding",
        11: "LCD Lock",
        13: "Video Encoding Duration",
        17: "Wireless Connections Enabled",
        19: "Pairing State",
        20: "Last Pairing Type",
        21: "Last Pairing Success",
        22: "Wifi Scan State",
        23: "Last Wifi Scan Success",
        24: "Wifi Provisioning State",
        26: "Remote Version",
        27: "Remote Connected",
        28: "Pairing State (Legacy)",
        29: "Connected WiFi SSID",
        30: "Access Point SSID",
        31: "Connected Devices",
        32: "Preview Stream",
        33: "Primary Storage",
        34: "Remaining Photos",
        35: "Remaining Video Time",
        38: "Photos",
        39: "Videos",
        41: "OTA",
        42: "Pending FW Update Cancel",
        45: "Locate",
        49: "Timelapse Interval Countdown",
        54: "SD Card Remaining",
        55: "Preview Stream Available",
        56: "Wifi Bars",
        58: "Active Hilights",
        59: "Time Since Last Hilight",
        60: "Minimum Status Poll Period",
        65: "Liveview Exposure Select Mode",
        66: "Liveview Y",
        67: "Liveview X",
        68: "GPS Lock",
        69: "AP Mode",
        70: "Internal Battery Percentage",
        74: "Microphone Accessory",
        75: "Zoom Level",
        76: "Wireless Band",
        77: "Zoom Available",
        78: "Mobile Friendly",
        79: "FTU",
        81: "5GHZ Available",
        82: "Ready",
        83: "OTA Charged",
        85: "Cold",
        86: "Rotation",
        88: "Zoom while Encoding",
        89: "Flatmode",
        93: "Video Preset",
        94: "Photo Preset",
        95: "Timelapse Preset",
        96: "Preset Group",
        97: "Preset",
        98: "Preset Modified",
        99: "Remaining Live Bursts",
        100: "Live Bursts",
        101: "Capture Delay Active",
        102: "Media Mod State",
        103: "Time Warp Speed",
        104: "Linux Core",
        105: "Lens Type",
        106: "Hindsight",
        107: "Scheduled Capture Preset ID",
        108: "Scheduled Capture",
        110: "Display Mod Status",
        111: "SD Card Write Speed Error",
        112: "SD Card Errors",
        113: "Turbo Transfer",
        114: "Camera Control ID",
        115: "USB Connected",
        116: "USB Controlled",
        117: "SD Card Capacity",
        118: "Photo Interval Capture Count",
    }

    STATUS_VALUES = {
        1: {
            0: "False",
            1: "True",
        },
        2: {
            0: "Zero",
            1: "One",
            2: "Two",
            3: "Three",
            4: "Charging",
        },
        6: {
            0: "False",
            1: "True",
        },
        8: {
            0: "False",
            1: "True",
        },
        9: {
            0: "False",
            1: "True",
        },
        10: {
            0: "False",
            1: "True",
        },
        11: {
            0: "False",
            1: "True",
        },
        17: {
            0: "False",
            1: "True",
        },
        19: {
            0: "Never Started",
            1: "Started",
            2: "Aborted",
            3: "Cancelled",
            4: "Completed",
        },
        20: {
            0: "Not Pairing",
            1: "Pairing App",
            2: "Pairing Remote Control",
            3: "Pairing Bluetooth Device",
        },
        22: {
            0: "Never started",
            1: "Started",
            2: "Aborted",
            3: "Canceled",
            4: "Completed",
        },
        24: {
            0: "Never started",
            1: "Started",
            2: "Aborted",
            3: "Canceled",
            4: "Completed",
        },
        27: {
            0: "False",
            1: "True",
        },
        32: {
            0: "False",
            1: "True",
        },
        33: {
            -1: "Unknown",
            0: "OK",
            1: "SD Card Full",
            2: "SD Card Removed",
            3: "SD Card Format Error",
            4: "SD Card Busy",
            8: "SD Card Swapped",
        },
        41: {
            0: "Idle",
            1: "Downloading",
            2: "Verifying",
            3: "Download Failed",
            4: "Verify Failed",
            5: "Ready",
            6: "GoPro App Downloading",
            7: "GoPro App Verifying",
            8: "GoPro App Download Failed",
            9: "GoPro App Verify Failed",
            10: "GoPro App Ready",
        },
        42: {
            0: "False",
            1: "True",
        },
        45: {
            0: "False",
            1: "True",
        },
        55: {
            0: "False",
            1: "True",
        },
        65: {
            0: "Disabled",
            1: "Auto",
            2: "ISO Lock",
            3: "Hemisphere",
        },
        68: {
            0: "False",
            1: "True",
        },
        69: {
            0: "False",
            1: "True",
        },
        74: {
            0: "Accessory not connected",
            1: "Accessory connected",
            2: "Accessory connected and a microphone is plugged into the accessory",
        },
        76: {
            0: "2.4 GHz",
            1: "5 GHz",
        },
        77: {
            0: "False",
            1: "True",
        },
        78: {
            0: "False",
            1: "True",
        },
        79: {
            0: "False",
            1: "True",
        },
        81: {
            0: "False",
            1: "True",
        },
        82: {
            0: "False",
            1: "True",
        },
        83: {
            0: "False",
            1: "True",
        },
        85: {
            0: "False",
            1: "True",
        },
        86: {
            0: "0 degrees (upright)",
            1: "180 degrees (upside down)",
            2: "90 degrees (laying on right side)",
            3: "270 degrees (laying on left side)",
        },
        88: {
            0: "False",
            1: "True",
        },
        101: {
            0: "False",
            1: "True",
        },
        102: {
            0: "Microphone removed",
            2: "Microphone only",
            3: "Microphone with external microphone",
        },
        103: {
            0: "15x",
            1: "30x",
            2: "60x",
            3: "150x",
            4: "300x",
            5: "900x",
            6: "1800x",
            7: "2x",
            8: "5x",
            9: "10x",
            10: "Auto",
            11: "1x (realtime)",
            12: "1/2x (slow-motion)",
        },
        104: {
            0: "False",
            1: "True",
        },
        105: {
            0: "Default",
            1: "Max Lens",
            2: "Max Lens 2.0",
            3: "Max Lens 2.5",
            4: "Macro Lens",
            5: "Anamorphic Lens",
            6: "Neutral Density 4",
            7: "Neutral Density 8",
            8: "Neutral Density 16",
            9: "Neutral Density 32",
        },
        106: {
            0: "False",
            1: "True",
        },
        108: {
            0: "False",
            1: "True",
        },
        110: {
            0: "000 = Display Mod: 0, HDMI: 0, Display Mod Connected: False",
            1: "001 = Display Mod: 0, HDMI: 0, Display Mod Connected: True",
            2: "010 = Display Mod: 0, HDMI: 1, Display Mod Connected: False",
            3: "011 = Display Mod: 0, HDMI: 1, Display Mod Connected: True",
            4: "100 = Display Mod: 1, HDMI: 0, Display Mod Connected: False",
            5: "101 = Display Mod: 1, HDMI: 0, Display Mod Connected: True",
            6: "110 = Display Mod: 1, HDMI: 1, Display Mod Connected: False",
            7: "111 = Display Mod: 1, HDMI: 1, Display Mod Connected: True",
        },
        111: {
            0: "False",
            1: "True",
        },
        113: {
            0: "False",
            1: "True",
        },
        114: {
            0: "Camera Idle: No one is attempting to change camera settings",
            1: "Camera Control: Camera is in a menu or changing settings. To intervene, app must request control",
            2: "Camera External Control: An outside entity (app) has control and is in a menu or modifying settings",
        },
        115: {
            0: "False",
            1: "True",
        },
        116: {
            0: "Disabled",
            1: "Enabled",
        },
    }

    SETTING_NAMES = {
        2: "Video Resolution",
        3: "Frames Per Second",
        5: "Video Timelapse Rate",
        30: "Photo Timelapse Rate",
        32: "Nightlapse Rate",
        43: "Webcam Digital Lenses",
        59: "Auto Power Down",
        83: "GPS",
        88: "LCD Brightness",
        91: "LED",
        108: "Video Aspect Ratio",
        121: "Video Lens",
        122: "Photo Lens",
        123: "Time Lapse Digital Lenses",
        125: "Photo Output",
        128: "Media Format",
        134: "Anti-Flicker",
        135: "Hypersmooth",
        150: "Video Horizon Leveling",
        151: "Photo Horizon Leveling",
        156: "Video Duration",
        157: "Multi Shot Duration",
        162: "Max Lens",
        167: "HindSight",
        168: "Scheduled Capture",
        171: "Photo Single Interval",
        172: "Photo Interval Duration",
        173: "Video Performance Mode",
        175: "Control Mode",
        176: "Easy Mode Speed",
        177: "Enable Night Photo",
        178: "Wireless Band",
        179: "Star Trails Length",
        180: "System Video Mode",
        182: "Video Bit Rate",
        183: "Bit Depth",
        184: "Profiles",
        186: "Video Easy Mode",
        187: "Lapse Mode",
        189: "Max Lens Mod",
        190: "Max Lens Mod Enable",
        191: "Easy Night Photo",
        192: "Multi Shot Aspect Ratio",
        193: "Framing",
        216: "Camera Volume",
        219: "Setup Screen Saver",
        223: "Setup Language",
        227: "Photo Mode",
        232: "Video Framing",
        233: "Multi Shot Framing",
        234: "Frame Rate",
    }

    SETTING_VALUES = {
        2: {
            1: "4K",
            4: "2.7K",
            6: "2.7K 4:3",
            7: "1440",
            9: "1080",
            12: "720",
            18: "4K 4:3",
            24: "5K",
            25: "5K 4:3",
            26: "5.3K 8:7",
            27: "5.3K 4:3",
            28: "4K 8:7",
            35: "5.3K 21:9",
            36: "4K 21:9",
            37: "4K 1:1",
            38: "900",
            100: "5.3K",
            107: "5.3K 8:7 V2",
            108: "4K 8:7 V2",
            109: "4K 9:16 V2",
            110: "1080 9:16 V2",
            111: "2.7K 4:3 V2",
            112: "4K 4:3 V2",
            113: "5.3K 4:3 V2",
        },
        3: {
            0: "240.0",
            1: "120.0",
            2: "100.0",
            5: "60.0",
            6: "50.0",
            8: "30.0",
            9: "25.0",
            10: "24.0",
            13: "200.0",
            15: "400.0",
            16: "360.0",
            17: "300.0",
        },
        5: {
            0: "0.5 Seconds",
            1: "1 Second",
            2: "2 Seconds",
            3: "5 Seconds",
            4: "10 Seconds",
            5: "30 Seconds",
            6: "60 Seconds",
            7: "2 Minutes",
            8: "5 Minutes",
            9: "30 Minutes",
            10: "60 Minutes",
            11: "3 Seconds",
        },
        30: {
            11: "3 Seconds",
            100: "60 Minutes",
            101: "30 Minutes",
            102: "5 Minutes",
            103: "2 Minutes",
            104: "60 Seconds",
            105: "30 Seconds",
            106: "10 Seconds",
            107: "5 Seconds",
            108: "2 Seconds",
            109: "1 Second",
            110: "0.5 Seconds",
        },
        32: {
            4: "4 Seconds",
            5: "5 Seconds",
            10: "10 Seconds",
            15: "15 Seconds",
            20: "20 Seconds",
            30: "30 Seconds",
            100: "60 Seconds",
            120: "2 Minutes",
            300: "5 Minutes",
            1800: "30 Minutes",
            3600: "60 Minutes",
            3601: "Auto",
        },
        43: {
            0: "Wide",
            2: "Narrow",
            3: "Superview",
            4: "Linear",
        },
        59: {
            0: "Never",
            1: "1 Min",
            4: "5 Min",
            6: "15 Min",
            7: "30 Min",
            11: "8 Seconds",
            12: "30 Seconds",
        },
        83: {
            0: "Off",
            1: "On",
        },
        91: {
            0: "Off",
            2: "On",
            3: "All On",
            4: "All Off",
            5: "Front Off Only",
            100: "Back Only",
        },
        108: {
            0: "4:3",
            1: "16:9",
            3: "8:7",
            4: "9:16",
            5: "21:9",
            6: "1:1",
        },
        121: {
            0: "Wide",
            2: "Narrow",
            3: "Superview",
            4: "Linear",
            7: "Max SuperView",
            8: "Linear + Horizon Leveling",
            9: "HyperView",
            10: "Linear + Horizon Lock",
            11: "Max HyperView",
            12: "Ultra SuperView",
            13: "Ultra Wide",
            14: "Ultra Linear",
            104: "Ultra HyperView",
        },
        122: {
            0: "Wide 12 MP",
            10: "Linear 12 MP",
            19: "Narrow",
            27: "Wide 23 MP",
            28: "Linear 23 MP",
            31: "Wide 27 MP",
            32: "Linear 27 MP",
            38: "13MP Linear",
            39: "13MP Wide",
            40: "13MP Ultra Wide",
            41: "Ultra Wide 12 MP",
            44: "13MP Ultra Linear",
            100: "Max SuperView",
            101: "Wide",
            102: "Linear",
        },
        123: {
            19: "Narrow",
            31: "Wide 27 MP",
            32: "Linear 27 MP",
            100: "Max SuperView",
            101: "Wide",
            102: "Linear",
        },
        125: {
            0: "Standard",
            1: "Raw",
            2: "HDR",
            3: "SuperPhoto",
        },
        128: {
            13: "Time Lapse Video",
            20: "Time Lapse Photo",
            21: "Night Lapse Photo",
            26: "Night Lapse Video",
        },
        134: {
            0: "NTSC",
            1: "PAL",
            2: "60Hz",
            3: "50Hz",
        },
        135: {
            0: "Off",
            1: "Low",
            2: "High",
            3: "Boost",
            4: "Auto Boost",
            100: "Standard",
        },
        150: {
            0: "Off",
            2: "Locked",
        },
        151: {
            0: "Off",
            2: "Locked",
        },
        156: {
            1: "15 Seconds",
            2: "30 Seconds",
            3: "1 Minute",
            4: "5 Minutes",
            5: "15 Minutes",
            6: "30 Minutes",
            7: "1 Hour",
            8: "2 Hours",
            9: "3 Hours",
            10: "5 Seconds",
            100: "No Limit",
        },
        157: {
            1: "15 Seconds",
            2: "30 Seconds",
            3: "1 Minute",
            4: "5 Minutes",
            5: "15 Minutes",
            6: "30 Minutes",
            7: "1 Hour",
            8: "2 Hours",
            9: "3 Hours",
            100: "No Limit",
        },
        162: {
            0: "Off",
            1: "On",
        },
        167: {
            2: "15 Seconds",
            3: "30 Seconds",
            4: "Off",
        },
        168: {
            0: "Is Scheduled Capture Enabled?",
            1: "Is 24 hour format?",
        },
        171: {
            0: "Off",
            2: "0.5s",
            3: "1s",
            4: "2s",
            5: "5s",
            6: "10s",
            7: "30s",
            8: "60s",
            9: "120s",
            10: "3s",
        },
        172: {
            0: "Off",
            1: "15 Seconds",
            2: "30 Seconds",
            3: "1 Minute",
            4: "5 Minutes",
            5: "15 Minutes",
            6: "30 Minutes",
            7: "1 Hour",
            8: "2 Hours",
            9: "3 Hours",
        },
        173: {
            0: "Maximum Video Performance",
            1: "Extended Battery",
            2: "Tripod / Stationary Video",
        },
        175: {
            0: "Easy",
            1: "Pro",
        },
        176: {
            0: "8X Ultra Slo-Mo",
            1: "4X Super Slo-Mo",
            2: "2X Slo-Mo",
            3: "1X Speed (Low Light)",
            4: "4X Super Slo-Mo (Ext. Batt.)",
            5: "2X Slo-Mo (Ext. Batt.)",
            6: "1X Speed (Ext. Batt.) (Low Light)",
            7: "8X Ultra Slo-Mo (50Hz)",
            8: "4X Super Slo-Mo (50Hz)",
            9: "2X Slo-Mo (50Hz)",
            10: "1X Speed (50Hz) (Low Light)",
            11: "4X Super Slo-Mo (50Hz) (Ext. Batt.)",
            12: "2X Slo-Mo (50Hz) (Ext. Batt.)",
            13: "1X Speed (50Hz) (Ext. Batt.) (Low Light)",
            14: "8X Ultra Slo-Mo (Ext. Batt.)",
            15: "8X Ultra Slo-Mo (50Hz) (Ext. Batt.)",
            16: "8X Ultra Slo-Mo (Long. Batt.)",
            17: "4X Super Slo-Mo (Long. Batt.)",
            18: "2X Slo-Mo (Long. Batt.)",
            19: "1X Speed (Long. Batt.) (Low Light)",
            20: "8X Ultra Slo-Mo (50Hz) (Long. Batt.)",
            21: "4X Super Slo-Mo (50Hz) (Long. Batt.)",
            22: "2X Slo-Mo (50Hz) (Long. Batt.)",
            23: "1X Speed (50Hz) (Long. Batt.) (Low Light)",
            24: "2X Slo-Mo (4K)",
            25: "4X Super Slo-Mo (2.7K)",
            26: "2X Slo-Mo (4K) (50Hz)",
            27: "4X Super Slo-Mo (2.7K) (50Hz)",
            100: "8X Ultra Slo-Mo (V2)",
            101: "4X Super Slo-Mo (V2)",
            102: "2X Slo-Mo (V2)",
            103: "1X Speed (Low Light) (V2)",
            104: "8X Ultra Slo-Mo (50Hz) (V2)",
            105: "4X Super Slo-Mo (50Hz) (V2)",
            106: "2X Slo-Mo (50Hz) (V2)",
            107: "1X Speed (50Hz) (Low Light) (V2)",
            108: "8X Ultra Slo-Mo (Long. Batt.) (V2)",
            109: "4X Super Slo-Mo (Long. Batt.) (V2)",
            110: "2X Slo-Mo (Long. Batt.) (V2)",
            111: "1X Speed (Long. Batt.) (Low Light) (V2)",
            112: "8X Ultra Slo-Mo (50Hz) (Long. Batt.) (V2)",
            113: "4X Super Slo-Mo (50Hz) (Long. Batt.) (V2)",
            114: "2X Slo-Mo (50Hz) (Long. Batt.) (V2)",
            115: "1X Speed (50Hz) (Long. Batt.) (Low Light) (V2)",
            116: "2X Slo-Mo (4K) (V2)",
            117: "2X Slo-Mo (4K) (50Hz) (V2)",
            118: "1X Speed (Low Light) (V2) (Vertical)",
            119: "1X Speed (50Hz) (Low Light) (V2) (Vertical)",
            120: "2X Slo-Mo (V2) (Vertical)",
            121: "2X Slo-Mo (50Hz) (V2) (Vertical)",
            122: "1X Speed (Full Frame) (Low Light) (V2)",
            123: "1X Speed (50Hz) (Full Frame) (Low Light) (V2)",
            124: "2X Slo-Mo (Full Frame) (V2)",
            125: "2X Slo-Mo (50Hz) (Full Frame) (V2)",
            126: "1X Speed (4K) (Low Light) (V2)",
            127: "1X Speed (4K) (50Hz) (Low Light) (V2)",
            128: "1X Speed (2.7K) (Low Light) (V2)",
            129: "1X Speed (2.7K) (50Hz) (Low Light) (V2)",
            130: "2X Slo-Mo (2.7K) (V2)",
            131: "2X Slo-Mo (2.7K) (50Hz) (V2)",
            132: "2X Slo-Mo (Long. Batt.) (V2) (Vertical)",
            133: "2X Slo-Mo (50Hz) (Long. Batt.) (V2) (Vertical)",
            134: "1X Speed (Long. Batt.) (Low Light) (V2) (Vertical)",
            135: "1X Speed (50Hz) (Long. Batt.) (Low Light) (V2) (Vertical)",
            136: "1X Speed (4K) (Full Frame) (Low Light) (V2)",
            137: "1X Speed (4K) (50Hz) (Full Frame) (Low Light) (V2)",
            138: "1X Normal Speed (1:1) (30 Fps) (4K) (V2)",
            139: "1X Normal Speed (1:1) (25 Fps) (4K) (V2)",
            140: "2X Slo-Mo Speed (1:1) (4K) (60 Fps) (V2)",
            141: "2X Slo-Mo Speed (1:1) (4K) (50 Fps) (V2)",
            142: "1X Normal Speed (21:9) (30 Fps) (5.3K) (V2)",
            143: "1X Normal Speed (21:9) (25 Fps) (5.3K) (V2)",
            144: "2X Slo-Mo Speed (21:9) (5.3K) (60 Fps) (V2)",
            145: "2X Slo-Mo Speed (21:9) (5.3K) (50 Fps) (V2)",
            146: "1X Normal Speed (21:9) (30 Fps) (4K) (V2)",
            147: "1X Normal Speed (21:9) (25 Fps) (4K) (V2)",
            148: "2X Slo-Mo Speed (21:9) (4K) (60 Fps) (V2)",
            149: "2X Slo-Mo Speed (21:9) (4K) (50 Fps) (V2)",
            150: "120 4X Super Slo-Mo Speed (21:9) (4K) (V2)",
            151: "100 4X Super Slo-Mo Speed (21:9) (4K) (V2)",
            152: "1X Normal Speed (30 Fps) (4:3) (5.3K) (V2)",
            153: "1X Normal Speed (25 Fps) (4:3) (5.3K) (V2)",
            154: "1X Normal Speed (30 Fps) (4:3) (4K) (V2)",
            155: "1X Normal Speed (25 Fps) (4:3) (4K) (V2)",
            156: "2X Slo-Mo Speed (4:3) (4K) (60 Fps) (V2)",
            157: "2X Slo-Mo Speed (4:3) (4K) (50 Fps) (V2)",
            158: "120 4X Super Slo-Mo Speed (2.7K) (4:3) (V2)",
            159: "100 4X Super Slo-Mo Speed (2.7K) (4:3) (V2)",
        },
        177: {
            0: "Off",
            1: "On",
        },
        178: {
            0: "2.4GHz",
            1: "5GHz",
        },
        179: {
            1: "Short",
            2: "Long",
            3: "Max",
        },
        180: {
            0: "Highest Quality",
            101: "Extended Battery",
            102: "Longest Battery",
            111: "Standard Quality",
            112: "Basic Quality",
        },
        182: {
            0: "Standard",
            1: "High",
        },
        183: {
            0: "8-Bit",
            2: "10-Bit",
        },
        184: {
            0: "Standard",
            1: "HDR",
            2: "Log",
            101: "HLG HDR",
        },
        186: {
            0: "Highest Quality",
            1: "Standard Quality",
            2: "Basic Quality",
            3: "Standard Video",
            4: "HDR Video",
        },
        187: {
            0: "TimeWarp",
            1: "Star Trails",
            2: "Light Painting",
            3: "Vehicle Lights",
            4: "Max TimeWarp",
            5: "Max Star Trails",
            6: "Max Light Painting",
            7: "Max Vehicle Lights",
            8: "Time Lapse Video",
            9: "Night Lapse Video",
        },
        189: {
            0: "None",
            1: "Max Lens 1.0",
            2: "Max Lens 2.0",
            3: "Max Lens 2.5",
            4: "Macro",
            5: "Anamorphic",
            6: "ND 4",
            7: "ND 8",
            8: "ND 16",
            9: "ND 32",
            10: "Standard Lens",
            100: "Auto Detect",
        },
        190: {
            0: "Off",
            1: "On",
        },
        191: {
            0: "Super Photo",
            1: "Night Photo",
            2: "Burst",
        },
        192: {
            0: "4:3",
            1: "16:9",
            3: "8:7",
            4: "9:16",
        },
        193: {
            0: "Widescreen",
            1: "Vertical",
            2: "Full Frame",
            100: "Traditional 4:3 v2",
            101: "Widescreen 16:9 v2",
            103: "Full Frame 8:7 v2",
            104: "Vertical 9:16 v2",
            105: "Ultra Widescreen 21:9 v2",
            106: "Full Frame 1:1 v2",
        },
        216: {
            70: "Low",
            85: "Medium",
            100: "High",
        },
        219: {
            1: "1 Min",
            2: "2 Min",
            3: "3 Min",
            4: "5 Min",
        },
        223: {
            0: "English - US",
            1: "English - UK",
            2: "English - AUS",
            3: "German",
            4: "French",
            5: "Italian",
            6: "Spanish",
            7: "Spanish - NA",
            8: "Chinese",
            9: "Japanese",
            10: "Korean",
            11: "Portuguese",
            12: "Russian",
            13: "English - IND",
            14: "Swedish",
        },
        227: {
            0: "SuperPhoto",
            1: "Night Photo",
            2: "Burst",
        },
        232: {
            0: "4:3",
            1: "16:9",
            3: "8:7",
            4: "9:16",
            5: "21:9",
            6: "1:1",
        },
        233: {
            0: "4:3",
            1: "16:9",
            3: "8:7",
            4: "9:16",
        },
        234: {
            0: "240.0",
            1: "120.0",
            2: "100.0",
            5: "60.0",
            6: "50.0",
            8: "30.0",
            9: "25.0",
            10: "24.0",
            13: "200.0",
            15: "400.0",
            16: "360.0",
            17: "300.0",
        },
    }
