{
 "title": "Fenetre.cam",
 "time": { "from": "2026-05-21T09:14:38.600Z", "to": "2026-05-21T17:26:10.907Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "camera",
    "label": "Camera name",
    "query": {
     "query": "label_values(pictures_taken_total,camera_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Camera status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "camera_online", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$host\", mountpoint=\"/\"}",
     "legendFormat": "Filesystem capacity"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$host\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=\"$host\", mountpoint=\"/\"}",
     "legendFormat": "total bytes used"
    },
    {
     "expr": "work_dir_size_bytes{}",
     "legendFormat": "{{instance}} - picture directory size"
    }
   ]
  },
  {
   "title": "SSIM vs sleep time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "camera_ssim_target{camera_name=\"$camera\"}",
     "legendFormat": "SSIM target"
    },
    {
     "expr": "camera_ssim_value{camera_name=\"$camera\"}",
     "legendFormat": "SSIM value"
    },
    {
     "expr": "capture_loop_sleep_time_seconds{camera_name=\"$camera\"}",
     "legendFormat": "Sleep time between pictures"
    }
   ]
  },
  {
   "title": "Total picture taken",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pic/h" } },
   "targets": [
    {
     "expr": "increase(pictures_taken_total{camera_name=\"$camera\"}[1h])",
     "legendFormat": "{{camera_name}}"
    },
    {
     "expr": "increase(pictures_taken_total{camera_name=\"$camera\"}[1h])/60",
     "legendFormat": "timelapse speed"
    }
   ]
  },
  {
   "title": "Camera exposure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ISO" } },
   "targets": [
    {
     "expr": "picture_iso{camera_name=\"$camera\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "picture_exposure_time_seconds{camera_name=\"$camera\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dir count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sum(dir_archived_count)", "legendFormat": "__auto" },
    { "expr": "sum(dir_total_count)", "legendFormat": "__auto" },
    { "expr": "sum(dir_daylight_count)", "legendFormat": "__auto" },
    { "expr": "sum(dir_timelapse_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Capture time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "capture_loop_sleep_time_seconds{camera_name=\"$camera\"} + capture_processing_time_seconds{camera_name=\"$camera\"}",
     "legendFormat": "{{camera_name}} - total loop time (processing + sleep)"
    },
    {
     "expr": "capture_processing_time_seconds{camera_name=\"$camera\"}",
     "legendFormat": "{{camera_name}} - processing time"
    },
    {
     "expr": "picture_exposure_time_seconds{camera_name=\"$camera\"}",
     "legendFormat": "{{camera_name}} - exposure time"
    }
   ]
  },
  {
   "title": "Exposure composite value",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "picture_iso * picture_exposure_time_seconds",
     "legendFormat": "{{camera_name}}"
    },
    {
     "expr": "camera_mode{camera_name=\"$camera\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "ISO",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "picture_iso", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "timelapses created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "timelapses_created_total{type=\"daily\"}",
     "legendFormat": "__auto"
    },
    { "expr": "timelapse_queue_size", "legendFormat": "__auto" }
   ]
  }
 ]
}